# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
  - job: SDL
    displayName: 'SDL Job for JS'
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: build/sdl-tasks.yml
