# Bump package version numbers and create a release branch
name: Automate Release

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version '
        required: true
      versionCode:
        description: 'Version #'
        required: true

jobs:
  release:
    name: Bump versions and create changelog PR --updation
    runs-on: ubuntu-latest
    steps:
       
       #get current date
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      

      # Install node_modules here
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            cache: 'npm'
      - run: npm ci

      - name: bump package versions
        run: npm run beachball:bump

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Release ; version bump; PR->master
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@microsoft.com>
          branch: releasev2/${{ steps.date.outputs.date }}
          title: 'Creating PR From :releasev2/${{ steps.date.outputs.date }}' 
          body: |
            New release PR
          draft: false
