# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: msal-angular E2E Tests

on:
  push:
    branches: 
      - dev
      - master
  pull_request:
    paths: 
      - 'lib/msal-angular/**/*'
      - 'lib/msal-browser/**/*' 
      - 'lib/msal-common/**/*'
      - 'samples/msal-angular-v2-samples/**/*'
      - '!**.md'
      - '.github/workflows/msal-angular-e2e.yml'

jobs:
  run-e2e:
    if: (github.repository == 'AzureAD/microsoft-authentication-library-for-js') && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        sample:
          - 'angular9-v2-sample-app'
          - 'angular10-sample-app'
          - 'angular11-b2c-sample'
          - 'angular11-sample-app'

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2

    - name: Clean Install
      env:
        RUNNING_NODE_CI: 1
      run: npm ci

    - name: Build packages
      working-directory: lib/msal-angular
      run: npm run build:all

    - name: Install Test Tools
      working-directory: samples/msal-angular-v2-samples
      run: npm install

    - name: Install ${{ matrix.sample }}
      working-directory: samples/msal-angular-v2-samples/${{ matrix.sample }}
      run: |
        npm install
    - name: Build ${{ matrix.sample }}
      working-directory: samples/msal-angular-v2-samples/${{ matrix.sample }}
      run: npm run build

    - name: E2E Tests
      working-directory: samples/msal-angular-v2-samples/${{ matrix.sample }}
      timeout-minutes: 5
      env:
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      run: npm run e2e

    - name: Upload E2E Test Screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: e2e-test-screenshots
        path: samples/**/screenshots