# NPM Publish is the name for this action
name: NPM Publish

# This action will trigger when Release PR from release-staging branch is merged into dev
on:
  pull_request_target:
    types: [closed]
    branches:
      - dev

concurrency:
  group: release-staging

# Job will run on a ubuntu instance
jobs:
  build:
    if: (github.event.pull_request.merged == true && github.head_ref == 'release-staging')
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      # Checkout the code
      - uses: actions/checkout@v2
        # Setup node with version 12.x and NPM registry url
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            core:
              - 'lib/msal-core/src/package.json'
            common: 
              - 'lib/msal-common/src/package.json'
            browser: 
              - 'lib/msal-browser/src/package.json'
            node:
              - 'lib/msal-node/src/package.json'
            angular:
              - 'lib/msal-angular/src/package.json'
            react:
              - 'lib/msal-react/src/package.json'
            node-extensions:
              - 'extensions/msal-node-extensions/package.json'
          list-files: json

      - name: Set npm auth token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"

      - name: Publish  msal-core
        if: steps.changes.outputs.core == 'true'
        working-directory: lib/msal-core
        env:
          CDN_EUNO_SAS: ${{ secrets.CDN_EUNO_SAS}}
          CDN_USWE_SAS: ${{ secrets.CDN_USWE_SAS}}
        run: |
          npm install
          npm run cdn
          npm publish

      - name: Publish  msal-common
        if: steps.changes.outputs.common == 'true'
        working-directory: lib/msal-common
        run: |
          npm install
          npm publish

      - name: Publish  msal-browser
        if: steps.changes.outputs.browser == 'true'
        working-directory: lib/msal-browser
        env:
          CDN_EUNO_SAS: ${{ secrets.CDN_EUNO_SAS}}
          CDN_USWE_SAS: ${{ secrets.CDN_USWE_SAS}}
        run: |
          npm install
          npm run cdn
          npm publish

      - name: Publish  msal-node
        if: steps.changes.outputs.node == 'true'
        working-directory: lib/msal-node
        run: |
          npm install
          npm publish

      - name: Publish  msal-angular
        if: steps.changes.outputs.angular == 'true'
        working-directory: lib/msal-angular
        run: |
          npm install
          npm run deploy

      - name: Publish  msal-react
        if: steps.changes.outputs.react == 'true'
        working-directory: lib/msal-react
        run: |
          npm install
          npm publish

      - name: Publish node-extensions
        if: steps.changes.outputs.node-extensions== 'true'
        working-directory: extensions/msal-node-extensions
        run: |
          npm install
          npm publish

      - name: Create Github Releases and Discussions
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN}}
        run: npm run beachball:release

      - name: Update package-locks
        run: npm install

      - name: Get release date
        id: release-date
        run: echo "::set-output name=date::$(node release-scripts/getReleaseDate.js -branch)"

      # Create Pull Request from post-release-month-year to dev
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Post-release
          branch: post-release-${{steps.release-date.outputs.date}}
          title: "${{ steps.release-date.outputs.date }} Post Release"
          body: |
            This PR contains package lock updates & cdn README updates for msal-browser and msal-core.
          draft: false
